### ISSUE TITLE
Some JS tests are failing

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-services#1748]
#1747 added `npm run test-client` command so we can run WCS JS unit tests. 

Some tests are currently failing:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/6209518/67723868-8600f400-f99a-11e9-80e2-dafcd0795bbe.png">

To reproduce:
1. Get latest `develop` and run `npm install`
1. Run `npm run test-client`

Failure list:
<details>

 FAIL  client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js
  ● Packages form reducer › DISMISS_MODAL

    Expected value   {"currentlyEditingPredefinedPackages": null, "modalErrors": {}, "showModal": false, "showOuterDimensions": false}
    Received:
      {"modalErrors": {}, "showModal": false, "showOuterDimensions": false}
    
    Message:
      expected { Object (showModal, modalErrors, ...) } to deeply equal { Object (modalErrors, showModal, ...) }

    Difference:

    - Expected
    + Received

      Object {
    -   "currentlyEditingPredefinedPackages": null,
        "modalErrors": Object {},
        "showModal": false,
        "showOuterDimensions": false,
      }

      109 | 		const state = reducer( visibleModalState, action );
      110 | 
    > 111 | 		expect( state ).to.eql( {
          | 		                   ^
      112 | 			modalErrors: {},
      113 | 			showModal: false,
      114 | 			showOuterDimensions: false,

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js:111:22)

  ● Packages form reducer › UPDATE_PACKAGES_FIELD

    Expected value   {"packageData": {"is_letter": false, "max_weight": "300", "name": "Box Test"}, "pristine": false}
    Received:
      {"packageData": {"is_letter": false, "max_weight": 0, "name": "Box Test"}, "pristine": false}
    
    Message:
      expected { Object (packageData, pristine) } to deeply equal { Object (packageData, pristine) }

    Difference:

    - Expected
    + Received

      Object {
        "packageData": Object {
          "is_letter": false,
    -     "max_weight": "300",
    +     "max_weight": 0,
          "name": "Box Test",
        },
        "pristine": false,
      }

      130 | 		const state = reducer( { packageData }, action );
      131 | 
    > 132 | 		expect( state ).to.eql( {
          | 		                   ^
      133 | 			packageData: {
      134 | 				name: 'Box Test',
      135 | 				max_weight: '300',

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js:132:22)

  ● Packages form reducer › SAVE_PREDEF

    Expected value   null
    Received:
      {"otherService": [], "service": ["box", "box1", "box2"]}
    
    Message:
      expected { Object (service, otherService) } to deeply equal null

    Difference:

      Comparing two different types of values. Expected null but received object.

      299 | 			otherService: [],
      300 | 		} );
    > 301 | 		expect( result.currentlyEditingPredefinedPackages ).to.eql( null );
          | 		                                                       ^
      302 | 		expect( result.pristine ).to.eql( false );
      303 | 		expect( result.showModal ).to.eql( false );
      304 | 	} );

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js:301:58)

 FAIL  client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js
  ● Shipping label selectors › getTotalPriceBreakdown - returns null when there are no rates selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:365:18)

  ● Shipping label selectors › getTotalPriceBreakdown - returns a breakdown when a rate is selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:394:18)

  ● Shipping label selectors › getTotalPriceBreakdown - returns a breakdown when one out of many rates is selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:439:18)

  ● Shipping label selectors › getTotalPriceBreakdown - returns a breakdown when many rates are selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:484:18)

 PASS  client/extensions/woocommerce/state/sites/shipping-classes/test/actions.js
 PASS  client/extensions/woocommerce/state/sites/settings/general/test/actions.js
 PASS  client/extensions/woocommerce/state/sites/shipping-classes/test/reducers.js
 PASS  client/extensions/woocommerce/state/sites/settings/general/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/review-replies/test/selectors.js
 PASS  client/extensions/woocommerce/state/ui/products/test/edits-reducer.js
 PASS  client/extensions/woocommerce/state/sites/settings/products/test/actions.js
 PASS  client/extensions/woocommerce/state/sites/orders/notes/test/selectors.js
 PASS  client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/actions.js
 PASS  client/extensions/woocommerce/state/ui/payments/currency/test/selectors.js
 FAIL  client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js
  ● Label purchase form reducer › WOOCOMMERCE_SERVICES_SHIPPING_LABEL_SET_PACKAGE_SIGNATURE updates package signature option and clears rates

    Expected value   ""
    Received:
      {"serviceId": "", "signatureRequired": false}
    
    Message:
      expected { Object (serviceId, signatureRequired) } to deeply equal ''

    Difference:

      Comparing two different types of values. Expected string but received object.

      458 | 		expect( state[ orderId ].form.packages.saved ).to.be.false;
      459 | 		expect( state[ orderId ].form.rates.available ).to.be.an( 'object' ).that.is.empty;
    > 460 | 		expect( state[ orderId ].form.rates.values.weight_0_custom1 ).to.eql( '' );
          | 		                                                                 ^
      461 | 	} );
      462 | 
      463 | 	it( 'WOOCOMMERCE_SERVICES_SHIPPING_LABEL_UPDATE_PACKAGE_WEIGHT updates package weight option and clears rates', () => {

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js:460:68)

  ● Label purchase form reducer › WOOCOMMERCE_SERVICES_SHIPPING_LABEL_UPDATE_PACKAGE_WEIGHT updates package weight option and clears rates

    Expected value   ""
    Received:
      {"serviceId": "", "signatureRequired": false}
    
    Message:
      expected { Object (serviceId, signatureRequired) } to deeply equal ''

    Difference:

      Comparing two different types of values. Expected string but received object.

      476 | 		expect( state[ orderId ].form.packages.saved ).to.be.false;
      477 | 		expect( state[ orderId ].form.rates.available ).to.be.an( 'object' ).that.is.empty;
    > 478 | 		expect( state[ orderId ].form.rates.values.weight_0_custom1 ).to.eql( '' );
          | 		                                                                 ^
      479 | 	} );
      480 | 
      481 | 	it( 'WOOCOMMERCE_SERVICES_SHIPPING_LABEL_CONFIRM_ADDRESS_SUGGESTION saves the address and proceeds to the next step', () => {

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js:478:68)

 PASS  client/extensions/woocommerce/state/sites/shipping-zone-methods/test/reducer.js
 PASS  client/extensions/woocommerce/state/sites/settings/products/test/selectors.js
 PASS  client/extensions/woocommerce/state/ui/review-replies/test/selectors.js
 PASS  client/extensions/woocommerce/state/ui/products/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/setup-choices/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/shipping-zone-locations/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/orders/activity-log/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/setup-choices/test/actions.js
 PASS  client/extensions/woocommerce/state/sites/payment-methods/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/orders/test/selectors.js
 PASS  client/extensions/woocommerce/state/ui/payments/methods/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/shipping-methods/test/selectors.js
 PASS  client/extensions/woocommerce/state/ui/products/variations/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/promotions/test/handlers.js
 PASS  client/extensions/woocommerce/state/ui/shipping/zones/methods/test/reducer.js
 PASS  client/extensions/woocommerce/state/sites/product-variations/test/selectors.js
 PASS  client/extensions/woocommerce/lib/analytics/test/tracks-utils.js
 PASS  client/extensions/woocommerce/state/sites/payment-methods/test/actions.js
 PASS  client/extensions/woocommerce/state/data-layer/products/test/index.js
 PASS  client/extensions/woocommerce/state/sites/shipping-zones/test/actions.js
 PASS  client/extensions/woocommerce/state/sites/products/test/selectors.js
 PASS  client/extensions/woocommerce/state/ui/reviews/test/selectors.js
 PASS  client/extensions/woocommerce/state/ui/shipping/zones/methods/test/selectors.js
 PASS  client/extensions/woocommerce/state/sites/shipping-methods/test/reducer.js

Summary of all failing tests
 FAIL  client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js
  ● Packages form reducer › DISMISS_MODAL

    Expected value   {"currentlyEditingPredefinedPackages": null, "modalErrors": {}, "showModal": false, "showOuterDimensions": false}
    Received:
      {"modalErrors": {}, "showModal": false, "showOuterDimensions": false}
    
    Message:
      expected { Object (showModal, modalErrors, ...) } to deeply equal { Object (modalErrors, showModal, ...) }

    Difference:

    - Expected
    + Received

      Object {
    -   "currentlyEditingPredefinedPackages": null,
        "modalErrors": Object {},
        "showModal": false,
        "showOuterDimensions": false,
      }

      109 | 		const state = reducer( visibleModalState, action );
      110 | 
    > 111 | 		expect( state ).to.eql( {
          | 		                   ^
      112 | 			modalErrors: {},
      113 | 			showModal: false,
      114 | 			showOuterDimensions: false,

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js:111:22)

  ● Packages form reducer › UPDATE_PACKAGES_FIELD

    Expected value   {"packageData": {"is_letter": false, "max_weight": "300", "name": "Box Test"}, "pristine": false}
    Received:
      {"packageData": {"is_letter": false, "max_weight": 0, "name": "Box Test"}, "pristine": false}
    
    Message:
      expected { Object (packageData, pristine) } to deeply equal { Object (packageData, pristine) }

    Difference:

    - Expected
    + Received

      Object {
        "packageData": Object {
          "is_letter": false,
    -     "max_weight": "300",
    +     "max_weight": 0,
          "name": "Box Test",
        },
        "pristine": false,
      }

      130 | 		const state = reducer( { packageData }, action );
      131 | 
    > 132 | 		expect( state ).to.eql( {
          | 		                   ^
      133 | 			packageData: {
      134 | 				name: 'Box Test',
      135 | 				max_weight: '300',

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js:132:22)

  ● Packages form reducer › SAVE_PREDEF

    Expected value   null
    Received:
      {"otherService": [], "service": ["box", "box1", "box2"]}
    
    Message:
      expected { Object (service, otherService) } to deeply equal null

    Difference:

      Comparing two different types of values. Expected null but received object.

      299 | 			otherService: [],
      300 | 		} );
    > 301 | 		expect( result.currentlyEditingPredefinedPackages ).to.eql( null );
          | 		                                                       ^
      302 | 		expect( result.pristine ).to.eql( false );
      303 | 		expect( result.showModal ).to.eql( false );
      304 | 	} );

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js:301:58)

 FAIL  client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js
  ● Shipping label selectors › getTotalPriceBreakdown - returns null when there are no rates selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:365:18)

  ● Shipping label selectors › getTotalPriceBreakdown - returns a breakdown when a rate is selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:394:18)

  ● Shipping label selectors › getTotalPriceBreakdown - returns a breakdown when one out of many rates is selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:439:18)

  ● Shipping label selectors › getTotalPriceBreakdown - returns a breakdown when many rates are selected

    TypeError: Cannot read property 'rates' of undefined

      137 | 		}
      138 | 		const { serviceId, signatureRequired } = selectedRates[ packageId ];
    > 139 | 		const packageRates = availableRates[ packageId ].default.rates;
          | 		                                                         ^
      140 | 		let signatureRates = null;
      141 | 		let foundRateSignatureRequired = null;
      142 | 		if ( 'signature_required' in availableRates[ packageId ] ) {

      at rates (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:139:60)
      at getTotalPriceBreakdown (client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js:134:43)
      at Object.<anonymous> (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js:484:18)

 FAIL  client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js
  ● Label purchase form reducer › WOOCOMMERCE_SERVICES_SHIPPING_LABEL_SET_PACKAGE_SIGNATURE updates package signature option and clears rates

    Expected value   ""
    Received:
      {"serviceId": "", "signatureRequired": false}
    
    Message:
      expected { Object (serviceId, signatureRequired) } to deeply equal ''

    Difference:

      Comparing two different types of values. Expected string but received object.

      458 | 		expect( state[ orderId ].form.packages.saved ).to.be.false;
      459 | 		expect( state[ orderId ].form.rates.available ).to.be.an( 'object' ).that.is.empty;
    > 460 | 		expect( state[ orderId ].form.rates.values.weight_0_custom1 ).to.eql( '' );
          | 		                                                                 ^
      461 | 	} );
      462 | 
      463 | 	it( 'WOOCOMMERCE_SERVICES_SHIPPING_LABEL_UPDATE_PACKAGE_WEIGHT updates package weight option and clears rates', () => {

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js:460:68)

  ● Label purchase form reducer › WOOCOMMERCE_SERVICES_SHIPPING_LABEL_UPDATE_PACKAGE_WEIGHT updates package weight option and clears rates

    Expected value   ""
    Received:
      {"serviceId": "", "signatureRequired": false}
    
    Message:
      expected { Object (serviceId, signatureRequired) } to deeply equal ''

    Difference:

      Comparing two different types of values. Expected string but received object.

      476 | 		expect( state[ orderId ].form.packages.saved ).to.be.false;
      477 | 		expect( state[ orderId ].form.rates.available ).to.be.an( 'object' ).that.is.empty;
    > 478 | 		expect( state[ orderId ].form.rates.values.weight_0_custom1 ).to.eql( '' );
          | 		                                                                 ^
      479 | 	} );
      480 | 
      481 | 	it( 'WOOCOMMERCE_SERVICES_SHIPPING_LABEL_CONFIRM_ADDRESS_SUGGESTION saves the address and proceeds to the next step', () => {

      at Object.eql (client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js:478:68)

**Comment by c-shultz** [comment]
FYI, it looks like a good chunk of the failures our due to my PR: https://github.com/Automattic/woocommerce-services/pull/1731
