### ISSUE TITLE
"DHL live rates available" notice causes fatal error when WC Admin is disabled

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-services#2400]
## Description

This was first reported in p1616690071123300-slack-C7U3Y3VMY mentioning a report in 3853620-zd-woothemes.

It seems that on sites where WC Admin is disabled, wp-admin becomes inaccessible due to an error caused by the "DHL live rates available" notice:

```
PHP Fatal error:  Uncaught Exception: Invalid data store. in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin')
#1 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/Note.php(87): WC_Data_Store::load('admin-note')
#2 /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-note-dhl-live-rates-available.php(37): Automattic\WooCommerce\Admin\Notes\Note->__construct()
#3 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/NoteTraits.php(74): WC_Connect_Note_DHL_Live_Rates_Available::get_note()
#4 /var/www/html/wp-content/plugins/woocommerce-services/classes/class-wc-connect-note-dhl-live-rates-available.php(27): WC_Connect_Note_DHL_Live_Rates_Available::possibly_add_note()
#5 /var/www/html/wp-content/plugins/woocommerce-services/woocommerce-services.php(746): WC_Connect_Note_DHL_Live_ in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 107
```

To be able to use wp-admin again, a site admin has to deactivate WCS&T or enable WC Admin.

## How to reproduce

WC Admin can be disabled using this filter:

```php
add_filter( 'woocommerce_admin_disabled', '__return_true' );
```

Tested on WP `5.7`, WC `5.1.0`, WCS&T `1.25.10`.

**Comment by phillipcornwell** [comment]
Also reported in 22743360-hc

We found that rolling back to 1.25.8 fixes the error.

**Comment by fylgjur** [comment]
Reported in forums: https://wordpress.org/support/topic/fatal-error-3831/
