### ISSUE TITLE
Plugin builds are very slow and contain `make` errors related to `fsevents`

### ISSUE THREAD

**Issue by waclawjacek** [Automattic/woocommerce-services#2565]
Attempts to build the plugin result in a really lengthy build. We need to look why this is the case.

## How to reproduce

1. Check out `trunk`
2. In the plugin directory, run: `nvm use && npm run prepare`
3. The build will take a really long time, seemingly stalling during `extractTree` or other steps (this is expected although not desired :)).
4. The build process will finish successfully but with errors.
5. The same issue will happen on subsequent attempts to run `npm run prepare`

An error like this should appear:

```
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit



gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node" "/Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents
gyp   SOLINK_MODULE(target) Release/fse.node
ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node /Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 21.5.0
node-pre-gyp ERR! command "/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node" "/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/Users/waclaw/.nvm/versions/node/v10.16.0/bin/node /Users/waclaw/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
  COPY /Users/waclaw/wcship/wp-calypso/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stampfsevents@1.2.7~install: fsevents@1.2.7
gyp info ok 
```

## Research done so far

I have done some research around this but I was unable to pinpoint the exact cause for this issue. I am including the findings so far:

1. Installing `python2` resolved some errors.
1. Then, discovered that the issue is with the `fsevents` library that two dependencies in wp-calypso are using (`chokidar` and another dependency prefixed with `jest-` - can't recall).
   * Calypso itself is pulled into WCS&T as a Git submodule.
1. The issue is that the binary for the specific version of `fsevents` is no longer available (IIRC, maintainer lost access to the server where binaries were hosted) and the library falls back to building the binary on your local machine instead. I think this is what is taking the most time.
   * Possible solution ideas (untested): upgrade Calypso version/try getting the binary to build.

**Comment by iyut** [comment]
Hi @waclawjacek , can you try to run this command in your terminal : `git config --global url.https://github.com/.insteadOf git://github.com/`. 

Can you confirm if it speed up the builds?

**Comment by waclawjacek** [comment]
Yes, it does! Great find! :rocket: The builds have sped up from the previous lengthy build of probably around 30-60 minutes to just:

```
441.26s user 135.30s system 201% cpu 4:46.53 total
```

Thank you! Do you know why exactly this sped up the build?

Also, it'd be great to resolve the build errors. Could you please continue the research on that?

**Comment by iyut** [comment]
@bartech actually the one that find this method 🥇  when he tried to configure his first wc services instances and found that the extracting took a long time. I just thought this method could be relevant with the issue. 

What it does actually adding these lines in your `.gitconfig` file : 
```
[url "https://github.com/"]
	insteadOf = git://github.com/
```

`npm` script actually use `git ls-remote` on some repo. By default, the repo URL is `git://...` and this URL seems not working for some reason . So by using that script, it changes the URL from `git://...` to `https://...` but we're still not sure why it's not working as of now.

Given the method seems working to speed up the build, do we still need to do anything for this task?

> Also, it'd be great to resolve the build errors. Could you please continue the research on that?

Yes, we're still working on that.

**Comment by waclawjacek** [comment]
That's brilliant, thanks so much! Kudos to @bartech for discovering this method! :tada:

> Given the method seems working to speed up the build, do we still need to do anything for this task?

I named this task "Plugin builds are very slow" because I was convinced that the *build* is actually taking this long, not pulling things via NPM. 🤔 But yeah, it'd be great if you could continue in this issue to resolve the build issues too.

**Comment by iyut** [comment]
A little update for this issue : I tried to update the wp-calypso version to [this commit](https://github.com/Automattic/wp-calypso/commit/79b83cb343521370813bc052b2789d3245cd9698). That commit will update the `fsevents` version from `1.2.7` to `1.2.8`, and It does fix the **fsevents** issue in `npm run prepare`.

However, there is some error when I run `npm run dist` and I'm still looking into this error.

```
ERROR in ./assets/stylesheets/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../../wp-calypso/calypso/images/checkbox-icons/checkmark-primary.svg' in '/Users/luthfibintoro/a8c/woocommerce-services/assets/stylesheets'
    at factory.create (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/webpack/lib/Compilation.js:925:10)
    at factory (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/luthfibintoro/a8c/woocommerce-services/node_modules/neo-async/async.js:2830:7
    at /Users/luthfibintoro/a8c/woocommerce-services/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
    at hook.callAsync (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/Users/luthfibintoro/a8c/woocommerce-services/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    ....
```
