### ISSUE TITLE
Potential conflict with Kadence WooCommerce Email Designer

### ISSUE THREAD

**Issue by kaushikasomaiya** [Automattic/woocommerce-services#2631]
5966229-zen

It appears that when hooks like `woocommerce_email_order_details` are executed - [mock order](https://wordpress.org/support/topic/fatal-error-when-used-with-woocommerce-shipment-tracking/) from Kadence causes fatal error triggered in Woo Shipping & Tax plugin.

```
2023-02-17T03:56:59+00:00 CRITICAL Uncaught Error: Call to a member function get_meta() on bool in /wordpress/plugins/woocommerce-services/2.2.3/classes/class-wc-connect-service-settings-store.php:244
Stack trace:
#0 /wordpress/plugins/woocommerce-services/2.2.3/woocommerce-services.php(1176): WC_Connect_Service_Settings_Store->get_label_order_meta_data(1)
#1 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(310): WC_Connect_Loader->add_tracking_info_to_emails(Object(WC_Order), false, false)
#2 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#3 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /srv/htdocs/wp-content/themes/seedlet-child/woocommerce/emails/email-order-details.php(90): do_action('woocommerce_ema...', Object(WC_Order), false, false, Object(WC_Email_Customer_Completed_Order))
#5 /wordpress/plugins/woocommerce/7.4.0/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#6 /wordpress/plugins/woocommerce/7.4.0/includes/class-wc-emails.php(421): wc_get_template('emails/email-or...', Array)
#7 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): WC_Emails->order_details(Object(WC_Order), false, false, Object(WC_Email_Customer_Completed_Order))
#8 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#9 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#10 /srv/htdocs/wp-content/themes/seedlet-child/woocommerce/emails/customer-completed-order.php(38): do_action('woocommerce_ema...', Object(WC_Order), false, false, Object(WC_Email_Customer_Completed_Order))
#11 /wordpress/plugins/woocommerce/7.4.0/includes/wc-core-functions.php(345): include('/srv/htdocs/wp-...')
#12 /wordpress/plugins/woocommerce/7.4.0/includes/wc-core-functions.php(364): wc_get_template('emails/customer...', Array, '', '')
#13 /wordpress/plugins/woocommerce/7.4.0/includes/emails/class-wc-email-customer-completed-order.php(109): wc_get_template_html('emails/customer...', Array)
#14 /wordpress/plugins/woocommerce/7.4.0/includes/emails/class-wc-email.php(572): WC_Email_Customer_Completed_Order->get_content_html()
#15 /srv/htdocs/wp-content/plugins/kadence-woocommerce-email-designer/includes/class-kadence-woomail-preview.php(740): WC_Email->get_content()
#16 /srv/htdocs/wp-content/plugins/kadence-woocommerce-email-designer/includes/class-kadence-woomail-preview.php(780): Kadence_Woomail_Preview::get_preview_email()
#17 /srv/htdocs/wp-content/plugins/kadence-woocommerce-email-designer/preview.php(40): Kadence_Woomail_Preview::print_preview_email()
#18 /srv/htdocs/wp-content/plugins/kadence-woocommerce-email-designer/includes/class-kadence-woomail-preview.php(200): include('/srv/htdocs/wp-...')
#19 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308): Kadence_Woomail_Preview->set_up_preview(Object(WP))
#20 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#21 /wordpress/core/6.1.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#22 /wordpress/core/6.1.1/wp-includes/class-wp.php(399): do_action_ref_array('parse_request', Array)
#23 /wordpress/core/6.1.1/wp-includes/class-wp.php(780): WP->parse_request('')
#24 /wordpress/core/6.1.1/wp-includes/functions.php(1332): WP->main('')
#25 /wordpress/core/6.1.1/wp-blog-header.php(16): wp()
#26 /wordpress/core/6.1.1/index.php(17): require('/wordpress/core...')
#27 {main}
  thrown in /wordpress/plugins/woocommerce-services/2.2.3/classes/class-wc-connect-service-settings-store.php on line 244
``` 

It appears that we are checking for Order here: 

https://github.com/Automattic/woocommerce-services/blob/4fedc542fc023c16c5a74eebdeafcac22aaabc78/woocommerce-services.php#L1170

However, the mock order with ID 1 doesn't return any order here:

https://github.com/Automattic/woocommerce-services/blob/4fedc542fc023c16c5a74eebdeafcac22aaabc78/classes/class-wc-connect-service-settings-store.php#L243

Does this need to be adjusted on WooCommerce Shipping & Tax? Or this is a bug in Kadence WooCommerce Email Designer?

**Comment by waclawjacek** [comment]
Looks like if in `WC_Connect_Service_Settings_Store::get_label_order_meta_data()` you replace

```php
public function get_label_order_meta_data( $order_id ) {
	$order      = wc_get_order( $order_id );
	$label_data = $order->get_meta( 'wc_connect_labels', true );
```

With:

```php
public function get_label_order_meta_data( $order_id ) {
	$order      = wc_get_order( $order_id );

	if ( ! $order ) {
		return array();
	}

	$label_data = $order->get_meta( 'wc_connect_labels', true );
```

This resolves it.
